#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MajordomeFinale.Droid.Resource", IsApplication=true)]

namespace MajordomeFinale.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int nb_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int badge90complete = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badgeCup = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badgeFire = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int badgeMap = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badgeMessage = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int badgeRunner = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int border = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Epicurien = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int imad = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int jacob = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Label_bio = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Label_Humain = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Label_vegan = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int lecedre = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Majordome_Logo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Restaurant = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Route = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int tacosgrenoble = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int Header = 2131099648;
			
			// aapt resource value: 0x7f060034
			public const int LoginEntry = 2131099700;
			
			// aapt resource value: 0x7f060038
			public const int MyButton = 2131099704;
			
			// aapt resource value: 0x7f060035
			public const int PasswordEntry = 2131099701;
			
			// aapt resource value: 0x7f060033
			public const int Welcome = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int WelcomeLogo = 2131099698;
			
			// aapt resource value: 0x7f06000f
			public const int accountBadges = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int accountBirthdate = 2131099660;
			
			// aapt resource value: 0x7f060039
			public const int accountFriends = 2131099705;
			
			// aapt resource value: 0x7f060002
			public const int accountLogin = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int accountMail = 2131099654;
			
			// aapt resource value: 0x7f060001
			public const int accountPP = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int accountPassword = 2131099657;
			
			// aapt resource value: 0x7f060017
			public const int accountRestaurant = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int badge1 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int badge2 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int badge3 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int badge4 = 2131099668;
			
			// aapt resource value: 0x7f060030
			public const int badge90complete = 2131099696;
			
			// aapt resource value: 0x7f060026
			public const int badgeCup = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int badgeFire = 2131099688;
			
			// aapt resource value: 0x7f06002a
			public const int badgeMap = 2131099690;
			
			// aapt resource value: 0x7f06002c
			public const int badgeMessage = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int badgeRunner = 2131099694;
			
			// aapt resource value: 0x7f060010
			public const int badgesContainer = 2131099664;
			
			// aapt resource value: 0x7f060025
			public const int badgesDescription = 2131099685;
			
			// aapt resource value: 0x7f060049
			public const int budget = 2131099721;
			
			// aapt resource value: 0x7f06003f
			public const int buttonCedre = 2131099711;
			
			// aapt resource value: 0x7f06003c
			public const int buttonEpicurien = 2131099708;
			
			// aapt resource value: 0x7f060042
			public const int buttonTacos = 2131099714;
			
			// aapt resource value: 0x7f06003e
			public const int cedre = 2131099710;
			
			// aapt resource value: 0x7f060046
			public const int cookType = 2131099718;
			
			// aapt resource value: 0x7f060020
			public const int emptySpace = 2131099680;
			
			// aapt resource value: 0x7f06003b
			public const int epicurien = 2131099707;
			
			// aapt resource value: 0x7f06000e
			public const int fieldBadges = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int fieldBirthdate = 2131099659;
			
			// aapt resource value: 0x7f060048
			public const int fieldBudget = 2131099720;
			
			// aapt resource value: 0x7f060045
			public const int fieldCookType = 2131099717;
			
			// aapt resource value: 0x7f06001d
			public const int fieldFriends = 2131099677;
			
			// aapt resource value: 0x7f06004b
			public const int fieldGrade = 2131099723;
			
			// aapt resource value: 0x7f060054
			public const int fieldLabels = 2131099732;
			
			// aapt resource value: 0x7f060005
			public const int fieldMail = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int fieldPassword = 2131099656;
			
			// aapt resource value: 0x7f06004e
			public const int fieldPhone = 2131099726;
			
			// aapt resource value: 0x7f060016
			public const int fieldRestaurants = 2131099670;
			
			// aapt resource value: 0x7f060051
			public const int fieldSchedule = 2131099729;
			
			// aapt resource value: 0x7f06001f
			public const int friend1 = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int friendsContainer = 2131099678;
			
			// aapt resource value: 0x7f06004c
			public const int grade = 2131099724;
			
			// aapt resource value: 0x7f06005b
			public const int imageView1 = 2131099739;
			
			// aapt resource value: 0x7f060003
			public const int infosContainer = 2131099651;
			
			// aapt resource value: 0x7f060056
			public const int label_bio = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int label_humain = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int label_vegan = 2131099736;
			
			// aapt resource value: 0x7f060055
			public const int labelsContainer = 2131099733;
			
			// aapt resource value: 0x7f06000d
			public const int lineBadges = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int lineBirthdate = 2131099658;
			
			// aapt resource value: 0x7f060047
			public const int lineBudget = 2131099719;
			
			// aapt resource value: 0x7f06001c
			public const int lineFriends = 2131099676;
			
			// aapt resource value: 0x7f06004a
			public const int lineGrade = 2131099722;
			
			// aapt resource value: 0x7f060053
			public const int lineLabels = 2131099731;
			
			// aapt resource value: 0x7f060004
			public const int lineMail = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int linePassword = 2131099655;
			
			// aapt resource value: 0x7f06004d
			public const int linePhone = 2131099725;
			
			// aapt resource value: 0x7f060015
			public const int lineRestaurants = 2131099669;
			
			// aapt resource value: 0x7f060050
			public const int lineSchedule = 2131099728;
			
			// aapt resource value: 0x7f06003a
			public const int linearLayout1 = 2131099706;
			
			// aapt resource value: 0x7f06003d
			public const int linearLayout2 = 2131099709;
			
			// aapt resource value: 0x7f060040
			public const int linearLayout3 = 2131099712;
			
			// aapt resource value: 0x7f060023
			public const int linkAccount = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int linkRestaurant = 2131099682;
			
			// aapt resource value: 0x7f060024
			public const int linkRoute = 2131099684;
			
			// aapt resource value: 0x7f060036
			public const int loginButton = 2131099702;
			
			// aapt resource value: 0x7f060021
			public const int navBarContainer = 2131099681;
			
			// aapt resource value: 0x7f06004f
			public const int phone = 2131099727;
			
			// aapt resource value: 0x7f06005a
			public const int reservation = 2131099738;
			
			// aapt resource value: 0x7f060019
			public const int restaurant1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int restaurant2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int restaurant3 = 2131099675;
			
			// aapt resource value: 0x7f060044
			public const int restaurantName = 2131099716;
			
			// aapt resource value: 0x7f060043
			public const int restaurantPP = 2131099715;
			
			// aapt resource value: 0x7f060018
			public const int restaurantsContainer = 2131099672;
			
			// aapt resource value: 0x7f060052
			public const int schedule = 2131099730;
			
			// aapt resource value: 0x7f060059
			public const int spinner = 2131099737;
			
			// aapt resource value: 0x7f060041
			public const int tacos = 2131099713;
			
			// aapt resource value: 0x7f060037
			public const int textView1 = 2131099703;
			
			// aapt resource value: 0x7f060031
			public const int titlebadge90complete = 2131099697;
			
			// aapt resource value: 0x7f060027
			public const int titlebadgeCup = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int titlebadgeFire = 2131099689;
			
			// aapt resource value: 0x7f06002b
			public const int titlebadgeMap = 2131099691;
			
			// aapt resource value: 0x7f06002d
			public const int titlebadgeMessage = 2131099693;
			
			// aapt resource value: 0x7f06002f
			public const int titlebadgeRunner = 2131099695;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BadgesDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PublicAccount = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Restaurant = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RestaurantDetail = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Route = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f04000d
			public const int FunctionTBD = 2130968589;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int LoginButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int TapeLogin = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int TapePassword = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int Welcome = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int fieldBadges = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int fieldBirthdate = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int fieldFriends = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int fieldMail = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int fieldPassword = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int fieldRestaurants = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int nbperson = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
